name: nyc_analytics_project
version: '1.0'
config-version: 2

profile: nyc_analytics_profile  # <-- must match your profiles.yml

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  nyc_analytics:
    assignment_work:
      staging:
        +materialized: table   # All staging models are tables
      marts:
        restaurant_applications:
          dim_date:
            +materialized: table  # dim_date is a table to avoid nested view errors